services:
  api:
    extends:
      file: docker-compose.yml
      service: api
    build:
      dockerfile: Dockerfile.prod
    command: sh -c "python manage.py migrate && gunicorn api.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DEBUG=0
