# Generated by Django 5.1.6 on 2025-02-12 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='VersionCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор')),
                ('version', models.CharField(max_length=50, verbose_name='Версия')),
                ('date_start_actual', models.DateField(blank=True, null=True, verbose_name='Дата начала действия версии')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.catalog', verbose_name='Идентификатор справочника')),
            ],
            options={
                'verbose_name': 'Версия справочника',
                'verbose_name_plural': 'Версии справочника',
            },
        ),
        migrations.CreateModel(
            name='ElementCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор')),
                ('code', models.CharField(max_length=100, verbose_name='Код элемента')),
                ('value', models.CharField(max_length=300, verbose_name='Значение элемента')),
                ('version_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.versioncatalog', verbose_name='Идентификатор версии справочника')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
            },
        ),
        migrations.AddConstraint(
            model_name='versioncatalog',
            constraint=models.UniqueConstraint(fields=('catalog', 'version'), name='unique_version_by_catalog'),
        ),
        migrations.AddConstraint(
            model_name='versioncatalog',
            constraint=models.UniqueConstraint(fields=('catalog', 'date_start_actual'), name='unique_start_date_by_catalog'),
        ),
        migrations.AddConstraint(
            model_name='elementcatalog',
            constraint=models.UniqueConstraint(fields=('version_catalog', 'code'), name='unique_element_code_per_by_version'),
        ),
    ]
