# Generated by Django 5.1.6 on 2025-02-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versioncatalog',
            old_name='data_start_actual',
            new_name='date_start_actual',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Код'),
        ),
        migrations.AddConstraint(
            model_name='elementcatalog',
            constraint=models.UniqueConstraint(fields=('version_catalog', 'code_element'), name='unique_element_code_per_by_version'),
        ),
        migrations.AddConstraint(
            model_name='versioncatalog',
            constraint=models.UniqueConstraint(fields=('catalog', 'version'), name='unique_version_by_catalog'),
        ),
        migrations.AddConstraint(
            model_name='versioncatalog',
            constraint=models.UniqueConstraint(fields=('catalog', 'date_start_actual'), name='unique_start_date_by_catalog'),
        ),
    ]
